"""
RAG pipeline for the Media Inclusivity Research Agent.
Auto-generated by day2_rag.ipynb Cell 12.
"""

import os
import json
from dotenv import load_dotenv
from pinecone import Pinecone
from openai import OpenAI

load_dotenv()

openai_client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
pc = Pinecone(api_key=os.getenv("PINECONE_API_KEY"))

with open("data/project_config.json", "r") as f:
    config = json.load(f)

index = pc.Index(config["pinecone_index_name"])


def rag_query(query: str, top_k: int = 3, angle_filter: str = None) -> list:
    """
    Query the Pinecone knowledge base and return relevant documents.

    Args:
        query: The research question to look up
        top_k: Number of results to return
        angle_filter: Optional - filter by research angle
            Options: bylines_and_story_selection, portrayal_in_content,
                     sourcing_diversity, language_and_framing

    Returns:
        List of dicts with keys: score, angle, text
    """
    query_embedding = openai_client.embeddings.create(
        model=config["embedding_model"],
        input=[query]
    ).data[0].embedding

    query_kwargs = {
        "vector": query_embedding,
        "top_k": top_k,
        "include_metadata": True
    }

    if angle_filter:
        query_kwargs["filter"] = {"angle": {"$eq": angle_filter}}

    results = index.query(**query_kwargs)

    return [
        {
            "score": match["score"],
            "angle": match["metadata"]["angle"],
            "text": match["metadata"]["text"]
        }
        for match in results["matches"]
    ]
