"""
report_generator.py
Structured Markdown Report Formatter for Media Diversity Watch

Takes the raw research summary produced by the ReAct agent and uses
a second LLM call to format it into a professional 11-section
inclusivity audit report.

Usage:
    from src.report_generator import generate_report, save_report

    report_md = generate_report("BBC", agent_result["final_analysis"])
    path = save_report("BBC", report_md)
"""

from datetime import date
from pathlib import Path

import anthropic
from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Report structure — 11 sections as defined in project_config.json
# ---------------------------------------------------------------------------
_REPORT_TEMPLATE = """\
You are a professional media analyst writing formal inclusivity audit reports \
for Media Diversity Watch, a non-profit research organisation.

Based on the research findings provided, write a structured Markdown report \
following the exact section headers below. Be specific — cite numbers and \
named examples from the research. Do not invent data not present in the findings.

IMPORTANT — data source constraints you must respect:
- RSS analysis covers headlines and short teasers only (not full article text). \
Community keyword hits reflect surface-level signal. Do not over-claim.
- RAG knowledge base provides industry benchmarks and research standards, \
not evidence specific to this outlet. Use it to contextualise scores, not as proof.
- NewsAPI returns article descriptions (1-2 sentences), not full coverage.
- Where evidence is thin, say so explicitly rather than filling gaps with assumptions.

Use this EXACT structure:

# {company}: Media Inclusivity Report

**Date:** {date}
**Organisation:** Media Diversity Watch
**Research Method:** Autonomous AI agent using ReAct pattern with RAG-backed knowledge base

---

## 1. Company Overview
[2–3 sentences on what the company is, ownership, reach, and editorial stance. \
Use Wikipedia data if available in the research.]

## 2. Bylines and Story Selection
[Who is writing the stories? Cite specific byline counts and author statistics \
from the RSS analysis. Note any gender or diversity gaps in authorship.]

## 3. Portrayal Within Content
[How are marginalised groups depicted in articles? Are they shown as experts \
and leaders, or primarily as victims and statistics? Use examples from the research.]

## 4. Sourcing Diversity
[Who gets quoted as an authority? Are community members treated as experts, \
or are outside voices used to speak about them? Cite specific findings.]

## 5. Language and Framing
[What language patterns were found? Note any harmful or non-inclusive terms \
flagged by the RSS analysis. Reference knowledge base benchmarks on best practice.]

## 6. Community-by-Community Findings

### Women and Gender Equality
[Specific findings on representation, portrayal, and language relating to women.]

### LGBTQ+ Communities
[Specific findings on representation, portrayal, and language relating to LGBTQ+ people.]

### Racial and Ethnic Minorities
[Specific findings on representation, portrayal, and language relating to race.]

### People with Disabilities
[Specific findings on representation, portrayal, and language relating to disability.]

## 7. Key Strengths
- [Bullet point: what the outlet does well, backed by evidence]
- [Bullet point]
- [Bullet point]

## 8. Areas of Concern and Harm Flags
- [Bullet point: concern with evidence]
- ⚠️ [Bullet point: serious harm flag if applicable]

## 9. Inclusivity Score

| Community | Score (1–10) | Justification |
|---|---|---|
| Women | X/10 | [one-line evidence-based justification] |
| LGBTQ+ | X/10 | [one-line evidence-based justification] |
| Race | X/10 | [one-line evidence-based justification] |
| Disability | X/10 | [one-line evidence-based justification] |
| **Overall Average** | **X/10** | |

Scoring guide: 9–10 = industry leader; 7–8 = above average; \
5–6 = meets minimum standards; 3–4 = below average; 1–2 = serious concerns.

## 10. Recommendations
1. [Specific, actionable recommendation with a clear owner and timeline]
2. [Specific, actionable recommendation]
3. [Specific, actionable recommendation]
4. [Specific, actionable recommendation — optional]

## 11. Sources and Evidence
- **RSS Feed analysis:** [outlet name], {date}, [N] articles reviewed
- **Knowledge base:** Media Diversity Watch internal benchmarks (Pinecone RAG)
- **NewsAPI:** Live article search, last 30 days
- **Wikipedia:** [article title used]

---

*Report generated by the Media Diversity Watch Autonomous Research Agent*
*Research: LangGraph ReAct agent (OpenAI gpt-4o-mini) · Report formatting: Anthropic claude-sonnet-4-6*

---

RESEARCH FINDINGS TO FORMAT:

{research_text}
"""


def generate_report(company: str, research_text: str) -> str:
    """
    Format raw agent research into a structured Markdown report.

    Args:
        company: Name of the media outlet
        research_text: Final analysis string from the ReAct agent

    Returns:
        Formatted Markdown report as a string
    """
    print(f"[REPORT] Formatting structured report for: {company}")

    client = anthropic.Anthropic()

    prompt = _REPORT_TEMPLATE.format(
        company=company,
        date=date.today().strftime("%d %B %Y"),
        research_text=research_text,
    )

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}],
    )
    return response.content[0].text


def generate_summary(company: str, report: str, overall_score: float) -> str:
    """
    Generate a 1-2 sentence plain-English summary suitable for a Notion
    database column — visible at a glance without opening the full report.

    Args:
        company: Name of the media outlet
        report: Full Markdown report
        overall_score: Parsed overall score (1-10)

    Returns:
        Short summary string (max ~200 chars)
    """
    client = anthropic.Anthropic()

    prompt = (
        f"Write exactly 1-2 sentences summarising {company}'s inclusivity audit result. "
        f"The overall score is {overall_score}/10. "
        f"Mention the score, the standout strength, and the main concern. "
        f"Keep it under 200 characters. Plain text only, no markdown.\n\n"
        f"Report excerpt:\n{report[:1500]}"
    )

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=256,
        messages=[{"role": "user", "content": prompt}],
    )
    return response.content[0].text.strip()


def save_report(company: str, report: str) -> Path:
    """
    Save the Markdown report to the reports/ directory.

    Args:
        company: Name of the media outlet
        report: Markdown report content

    Returns:
        Path to the saved file
    """
    reports_dir = Path(__file__).parent.parent / "reports"
    reports_dir.mkdir(exist_ok=True)

    safe_name = company.lower().replace(" ", "_").replace("/", "-")
    filename = f"{safe_name}_{date.today().isoformat()}.md"
    filepath = reports_dir / filename

    filepath.write_text(report, encoding="utf-8")
    print(f"[REPORT] Saved to: {filepath}")

    return filepath
